apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-api-deployment
  labels:
    app: be-api
spec:
  replicas: 2
  strategy: 
    type: RollingUpdate
    rollingUpdate:      
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: be-api
  template:
    metadata:
      labels:
        app: be-api
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: be-api-container
        image: 127.0.0.1:5001/spring-k8s:v1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "150m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 15
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 30"]
        env:
        - name: JAVA_TOOL_OPTIONS
          value: '-XX:MinRAMPercentage=80.0'
        - name: SERVER_PORT
          value: '8080'
        - name: SPRING_PROFILES_ACTIVE
          value: 'dev'
---
apiVersion: v1
kind: Service
metadata:
  name: be-api-svc
spec:
  selector:
    app: be-api
  type: LoadBalancer
  externalIPs:
  - 10.0.1.1
  - 10.0.1.10
  ports:
  - name: http
    port: 8888
    targetPort: 8080 
