version: '3.8'

services:
  db:
    image: mysql:5.7.40
    ports:
      - "127.0.0.1:3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=<database>
      - MYSQL_USER=<username>
      - MYSQL_PASSWORD=<password>
      - MYSQL_ROOT_PASSWORD=<root password>
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - bridge-net

volumes:
  db-data:
    external: false

networks:
  bridge-net:
    driver: bridge
