version: '3.8'

services:
  db:
    image: mysql:5.7.40
    container_name: mysql-5.7.40
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=demo_db
      - MYSQL_USER=zclouds
      - MYSQL_PASSWORD=abc13579!@
      - MYSQL_ROOT_PASSWORD=zclouds123!@

    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - db-data:/var/lib/mysql
    networks:
      - shared_net

volumes:
  db-data:

networks:
  shared_net:
